# to build this dockerfile, run below:
# nvidia-docker build -t $USER/cuda-py-docker:latest .

# to run the container of this image, run below:
# nvidia-docker run -ti -h docker-minitorch -v $(pwd):/root/your_dir:rw --name minitorch $USER/cuda-py-docker:latest
# add --rm if you want kill the container right after exit

FROM nvidia/cuda:11.6.0-devel-ubuntu20.04
MAINTAINER austin

# install preliminaries
RUN apt update && apt upgrade -y
RUN apt install git curl zsh python3 python3-pip -y

# install monitoring tools
RUN pip3 install bpytop gpustat

# install oh-my-zsh
RUN sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

# install zsh theme "pure"
RUN mkdir -p "$HOME/.zsh-theme"
RUN git clone https://github.com/sindresorhus/pure.git "$HOME/.zsh-theme/pure"
RUN echo "fpath+=$HOME/.zsh-theme/pure\n \
          autoload -U promptinit; promptinit\n \
          zstyle :prompt:pure:git:stash show yes\n \
          zstyle :prompt:pure:path color '#40826d'\n \
          zstyle :prompt:pure:prompt:success color '#01DF01'\n \
          zstyle :prompt:pure:virtualenv color '#11a3a2'\n \
          zstyle :prompt:pure:git:branch color '#808080'\n \
          zstyle :prompt:pure:user color 'ffc100'\n \
          zstyle :prompt:pure:host color 'ffc100'\n \
          prompt pure" >> ~/.zshrc

# install miniconda3
# RUN sh -c "$(curl -o ~/miniconda3.sh https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh)"
# RUN sh ~/miniconda3.sh -b -p && \
#     rm ~/miniconda3.sh
# RUN ~/miniconda3/bin/conda clean -tipsy && \
#     ln -s ~/miniconda3/etc/profile.d/conda.sh /etc/profile.d/conda.sh && \
#     echo ". ~/miniconda3/etc/profile.d/conda.sh\n \
#           conda activate base" >> ~/.zshrc

WORKDIR /root/your_dir

CMD [ "/bin/zsh" ]